layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  medium: @tcbyrd
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: _tcbyrd
  # youtube: your_username
  # vk: your_username

topics:
  - name: Probot
    web_url: https://probot.github.io
    image_url: https://probot.github.io/assets/logo.png

  - name: NodeJS
    web_url: https://nodejs.org/en/
    image_url: https://nodejs.org/static/images/logo.svg

  - name: Video
    web_url: https://github.com/topics/video
    image_url: https://user-images.githubusercontent.com/13207348/54175985-1ad5d200-444a-11e9-9e69-f366a1c85d53.png
